version: "2"
sql:
  - engine: "postgresql"
    queries: "postgres"
    schema: "schema.sql"
    gen:
      go:
        package: "sqlgen"
        out: "postgres/sqlgen"
        sql_package: "pgx/v5"
        emit_interface: true
        emit_result_struct_pointers: true
        emit_pointers_for_null_types: true
        emit_json_tags: true
        overrides:
          - db_type: "timestamptz"
            go_type: "time.Time"
          - db_type: "timestamptz"
            go_type:
              type: "time.Time"
              pointer: true
            nullable: true
          - db_type: "pg_catalog.int4"
            go_type: "int"
          - db_type: jsonb
            go_type:
              import: "encoding/json"
              type: "RawMessage"
          - db_type: jsonb
            go_type:
              import: "encoding/json"
              type: "RawMessage"
            nullable: true