// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlgen

import (
	"encoding/json"
	"time"
)

type Contest struct {
	ID          string    `json:"id"`
	CreatorID   string    `json:"creator_id"`
	Title       string    `json:"title"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type EloHistory struct {
	ID        string    `json:"id"`
	ItemID    string    `json:"item_id"`
	EloRating int       `json:"elo_rating"`
	CreatedAt time.Time `json:"created_at"`
}

type Item struct {
	ID          string          `json:"id"`
	ContestID   string          `json:"contest_id"`
	ContentType string          `json:"content_type"`
	Content     json.RawMessage `json:"content"`
	EloRating   int             `json:"elo_rating"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type User struct {
	ID           string    `json:"id"`
	DisplayName  string    `json:"display_name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Vote struct {
	ID           string    `json:"id"`
	ContestID    string    `json:"contest_id"`
	UserID       string    `json:"user_id"`
	WinnerItemID string    `json:"winner_item_id"`
	LoserItemID  string    `json:"loser_item_id"`
	CreatedAt    time.Time `json:"created_at"`
}
