package postgres

import (
	"context"
	"errors"
	"fmt"

	"rankit/postgres/sqlgen"

	"github.com/jackc/pgerrcode"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
)

func Connect(URI string) (*pgxpool.Pool, error) {
	pool, err := pgxpool.New(context.Background(), URI)
	if err != nil {
		return nil, fmt.Errorf("failed to connect to database: %w", err)
	}

	err = pool.Ping(context.Background())
	if err != nil {
		return nil, fmt.Errorf("failed to ping database: %w", err)
	}

	return pool, nil
}

// Querier interface generated by sqlc doesn't have a WithTx method generated on it.
// So we have to roll our own
type TxnQuerier interface {
	sqlgen.Querier
	WithTx(pgx.Tx) TxnQuerier
}

type TransactionalQuerier struct {
	*sqlgen.Queries
}

func (q *TransactionalQuerier) WithTx(txn pgx.Tx) TxnQuerier {
	return &TransactionalQuerier{sqlgen.New(txn)}
}

var _ TxnQuerier = (*TransactionalQuerier)(nil)

func NewQuerier(pool *pgxpool.Pool) *TransactionalQuerier {
	return &TransactionalQuerier{sqlgen.New(pool)}
}

func IsUniqueViolation(err error) (*pgconn.PgError, bool) {
	var pgErr *pgconn.PgError
	ok := errors.As(err, &pgErr)
	return pgErr, ok && pgErr.Code == pgerrcode.UniqueViolation
}

func IsNotFound(err error) bool {
	return errors.Is(err, pgx.ErrNoRows)
}

func IsForeignKeyViolation(err error) (*pgconn.PgError, bool) {
	var pgErr *pgconn.PgError
	ok := errors.As(err, &pgErr)
	return pgErr, ok && pgErr.Code == pgerrcode.ForeignKeyViolation
}
